name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout sololearn-coding-challenges
        uses: actions/checkout@v2
        with:
            path: challenges
      - name: v fmt -verify
        run: ./v fmt -verify challenges/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout sololearn-coding-challenges
        uses: actions/checkout@v2
        with:
            path: challenges
      - name: Run tests
        run: ./v test challenges
