name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout sololearn-coding-challenges
        uses: actions/checkout@v2
        with:
            path: challenges
      - name: Run vet
        run: ./v vet challenges/
      - name: Verify formatting
        run: |
          ./v fmt -verify challenges/
          ./v fmt -diff challenges/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout sololearn-coding-challenges
        uses: actions/checkout@v2
        with:
            path: challenges
      - name: Run tests
        run: ./v test challenges
      - name: Run tests with warnings as errors
        run: ./v -W test challenges
