name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master
        id: v
      - name: Check formatting
        run: v run fmt_verify_all.vsh
      - name: Run tests
        run: v test .
